//
// Created by serge on 02.10.2021.
//

#ifndef LINUX_TASK_CHECKER_CONFIG_H
#define LINUX_TASK_CHECKER_CONFIG_H

#define STRINGIZER(arg)     #arg
#define STR_VALUE(arg)      STRINGIZER(arg)
#define CONFIG_WITH_LMS_CHECKING STR_VALUE(LMS_INTEGRATION)
//#define CONFIG_WITH_LMS_CHECKING "1"
#define CONFIG_BASE_URL LMS_BASE_URL

#define CONFIG_USER_ID USER_ID_LMS
#define CONFIG_USER_NAME USER_NAME_LMS
#define CONFIG_COURSE_ID COURSE_ID_LMS

#define CONFIG_PASS_ROBOT PASS_LMS_ROBOT
#define CONFIG_HASH_PASS_ROBOT HASH_PASS_LMS_ROBOT

#define CONFIG_ZERO_TASK ZERO_TASK_ID
#define CONFIG_FIRST_TASK FIRST_TASK_ID
#define CONFIG_SECOND_TASK SECOND_TASK_ID
#define CONFIG_THIRD_TASK THIRD_TASK_ID
#define CONFIG_FOURTH_TASK FOURTH_TASK_ID
#define CONFIG_FIFTH_TASK FIFTH_TASK_ID
#define CONFIG_SIXTH_TASK SIXTH_TASK_ID
#define CONFIG_SEVENTH_TASK SEVENTH_TASK_ID
#define CONFIG_EIGHTH_TASK EIGHTH_TASK_ID
#define CONFIG_NINTH_TASK NINTH_TASK_ID
#define CONFIG_TENTH_TASK TENTH_TASK_ID

#endif //LINUX_TASK_CHECKER_CONFIG_H
