//
// Created by serge on 02.10.2021.
//

#ifndef LINUX_TASK_CHECKER_CONFIG_H
#define LINUX_TASK_CHECKER_CONFIG_H

#define STRINGIZER(arg)     #arg
#define STR_VALUE(arg)      STRINGIZER(arg)
#define CONFIG_WITH_LMS_CHECKING STR_VALUE(LMS_INTEGRATION)
//#define CONFIG_WITH_LMS_CHECKING "1"
#define CONFIG_BASE_URL LMS_BASE_URL

#define CONFIG_USER_ID USER_ID_LMS
#define CONFIG_USER_NAME USER_NAME_LMS
#define CONFIG_COURSE_ID COURSE_ID_LMS

#define CONFIG_PASS_CODE PASS_CODE
#define CONFIG_HASH_PASS_CODE HASH_PASS_CODE

#define CONFIG_ZERO_TASK "0"
#define CONFIG_FIRST_TASK "1"
#define CONFIG_SECOND_TASK "2"
#define CONFIG_THIRD_TASK "3"
#define CONFIG_FOURTH_TASK "4"
#define CONFIG_FIFTH_TASK "5"
#define CONFIG_SIXTH_TASK "6"
#define CONFIG_SEVENTH_TASK "7"
#define CONFIG_EIGHTH_TASK "8"
#define CONFIG_NINTH_TASK "9"
#define CONFIG_TENTH_TASK TENTH_TASK_ID

#endif //LINUX_TASK_CHECKER_CONFIG_H
