# Generated by Django 4.2.4 on 2023-08-20 15:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="access_token",
            field=models.CharField(
                default=app.models.generate_token, max_length=100, unique=True
            ),
        ),
    ]
