# Generated by Django 4.2.4 on 2023-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_student_canvas_lms_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="canvas_lms_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
