# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false
#   config.vm.network "forwarded_port", guest: 22, host: 2221

  config.vm.provision "shell", inline: <<-SHELL
    echo "course" | sudo passwd --stdin "course"
#     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd.service
    apt-get update
    apt-get install -y php postgresql postgresql-contrib
  SHELL

end
